trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'sonarcloud-connection'
      organization: 'my-demo-origination-azure'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'my-demo-project'
      cliSources: '.'
      displayName: Preparing Connection between SonarCloud and Azure Pipeline
  
  - template: templates/build.yaml
    parameters:
      buildConfiguration: "install"
  
  - task: SonarCloudAnalyze@1
    displayName: Analysing the code
  
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    displayName: Sending the result

