trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'sonarcloud-connection'
      organization: 'my-demo-origination-1'
      scannerMode: 'Other'
      sonar.exclusions=**/*.bin
    displayName: Preparing Connection between SonarCloud and Azure Pipeline
  
  - template: templates/build.yaml
    parameters:
      buildConfiguration: "install"

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    displayName: Sending the result


